"""
InvoiceRenderer — *** BONUS / OPTIONAL — NOT REQUIRED FOR THE CORE PROJECT ***

The core project uses a plain-text invoice format (see
`billing_engine.cli.format_invoice_text`). This PDF renderer is provided as a
**bonus exercise** for students who want to explore the `reportlab` library.

To attempt the bonus:
    1. Install reportlab:  `pip install reportlab`
    2. Implement the methods below.
    3. (Optional) wire `billing invoice show <id> --pdf` in cli.py.

NO tests cover this module — the bonus is graded by visual inspection of the
output PDF only.

Resource: https://www.reportlab.com/docs/reportlab-userguide.pdf
"""

from __future__ import annotations
from decimal import Decimal

from pathlib import Path
from typing import Iterable

from billing_engine.models import Customer, Invoice, InvoiceLineItem
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4


class InvoiceRenderer:
    """BONUS — only implement if you want to explore PDF generation."""

    def __init__(self, output_dir: str | Path = "invoices") -> None:
        # BONUS — see module docstring.
        #   - Convert output_dir to Path.
        #   - Create the directory if it doesn't exist (mkdir parents=True, exist_ok=True).
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(
            parents=True,
            exist_ok=True
            )


    def render(
        self,
        invoice: Invoice,
        customer: Customer,
        line_items: Iterable[InvoiceLineItem],
    ) -> Path:
        """Write the PDF and return its absolute path. BONUS.

        Suggested sections:
            1. Header:  "INVOICE" + invoice id + issued date
            2. Customer block: name, email, country
            3. Period: "Billing period: <start> to <end>"
            4. Line items table: description | amount
            5. Totals: subtotal, discount, tax, TOTAL (bold)
            6. Footer: "Generated by Billing Engine"

        Hints:
            - Use reportlab.pdfgen.canvas.Canvas with reportlab.lib.pagesizes.A4.
            - File path: self.output_dir / f"INV-{invoice.id}.pdf".
            - Draw each section using c.drawString / c.drawRightString.
            - c.save() at the end.
            - Return the resolved Path.
        """
        file_path = self.output_dir / f"INV-{invoice.id}.pdf"
        c = canvas.Canvas(
            str(file_path),
            pagesize=A4
            )
        
        width, height = A4
        # -------- HEADER --------

        c.setFont("Helvetica-Bold",18)
        c.drawString(50,height - 50,"INVOICE")
        c.line(50,height - 60,550,height - 60)
        c.setFont("Helvetica",12)
        c.drawString(50,height - 80,f"Invoice ID: {invoice.id}")
        c.drawString(50,height - 100,f"Issued Date: {invoice.issued_at}")

        # -------- CUSTOMER DETAILS --------
        y = height - 150
        c.drawString(50,y,"Customer Details:") 
        c.drawString(50,y-20,f"Name: {customer.name}")
        c.drawString(50,y-40,f"Email: {customer.email}")
        c.drawString(50,y-60,f"State Code: {customer.state_code}")
        c.drawString(50,y-80,f"Country Code: {customer.country_code}")

        # -------- BILLING PERIOD --------
        y -= 120
        c.drawString(50,y,f"Billing period: {invoice.period_start} to {invoice.period_end}")
        
        # -------- LINE ITEMS --------
        y -= 50
        c.setFont("Helvetica-Bold",12)
        c.drawString(50,y,"Description")
        c.drawString(350,y,"Amount")
        c.line(50,y - 5,450,y - 5)
        c.setFont("Helvetica",12)
        y -= 25
        subtotal = 0
        for item in line_items:
            c.drawString(50,y,item.description)
            c.drawRightString(400,y,str(item.amount))
            subtotal += item.amount.amount
            y -= 20
        
        
        # -------- TOTALS --------
        y -= 30
        c.drawString(50,y,f"Subtotal: {subtotal}")
        c.drawString(50,y-20,f"Discount: {invoice.discount_total}")
        c.drawString(50,y-40,f"Tax: {invoice.tax_total}")
        c.line(50,y - 55,450,y - 55)
        c.setFont("Helvetica-Bold",12)
        c.drawString(50,y-70,f"TOTAL: {invoice.total}")
        
        # -------- FOOTER --------
        c.setFont("Helvetica",10)
        c.line(50,70,550,70)
        c.drawString(50,50,"Generated by Billing Engine")
        
        
        # Save PDF
        c.save()
        return file_path.resolve()
